import { NextResponse } from "next/server";
import type { Mushak91Data } from "@/types/mushak";

export async function POST(req: Request) {
  const data: Mushak91Data = await req.json();

  // Simple HTML-based PDF (print-ready). In production add @react-pdf/renderer or puppeteer.
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Mushak 9.1 – ${data.period.startDate}</title>
      <style>
        body { font-family: system-ui; padding: 40px; background: white; color: black; }
        .header { text-align: center; font-size: 24px; font-weight: bold; margin-bottom: 30px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #000; padding: 12px; text-align: left; }
        .net { font-size: 32px; font-weight: bold; text-align: center; padding: 30px; border: 3px solid #000; }
      </style>
    </head>
    <body>
      <div class="header">Mushak 9.1 – Monthly VAT Return<br>INSPIRON TECH BD</div>
      <p><strong>Business:</strong> ${data.businessName} | <strong>BIN:</strong> ${data.bin}</p>
      <p><strong>Period:</strong> ${data.period.startDate} to ${data.period.endDate} | Due: ${data.period.dueDate}</p>
      
      <table>
        <tr><th>Output VAT (6.3)</th><td>৳ ${data.outputVAT.toLocaleString("en-IN")}</td></tr>
        <tr><th>Input Credit (6.4)</th><td>৳ ${data.inputCredit.toLocaleString("en-IN")}</td></tr>
        <tr><th>Net VAT Payable</th><td class="net">৳ ${data.netPayable.toLocaleString("en-IN")}</td></tr>
      </table>
      
      <p style="text-align:center; margin-top:60px; font-size:12px;">
        Generated by INSPIRON VAT Engine • ${data.generatedAt} • n-Law 01 Compliant
      </p>
    </body>
    </html>
  `;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html",
      "Content-Disposition": `attachment; filename="Mushak-91-${data.period.startDate}.html"`,
    },
  });
}
